### ISSUE TITLE
Support for S3 Transfer Acceleration

### ISSUE THREAD

**Issue by juan-luna** [MikeSouza/serverless-deployment-bucket#19]
Currently using S3 Transfer Acceleration in our organization for our pipelines.
We deploy with:
serverless deploy --verbose --conceal --aws-s3-accelerate --stage dev

Therefore, we can't use this plugin:

![Captura de pantalla 2020-09-04 a la(s) 12 18 37 p  m](https://user-images.githubusercontent.com/52544046/92269063-0c367280-eea9-11ea-98d3-b8d32e191a5d.png)

We'd appreciate a custom option to create the s3 with Transfer Acceleration enabled.

**Comment by MikeSouza** [comment]
@henriksvensson Thank you for contribution.

**Comment by henriksvensson** [comment]
Thanks for your plugin and quick merge, @MikeSouza. Happy to contribute!
