### ISSUE TITLE
deploymentBucket is ignored

### ISSUE THREAD

**Issue by jameswoodley** [MikeSouza/serverless-deployment-bucket#24]
It seems with the latest versions of serverless & serverless-deployment-bucket, the provider.deploymentBucket object is ignored. I am getting

```
 Serverless Error ---------------------------------------

  Could not locate deployment bucket. Error: The specified bucket does not exist
```

If I change `provider.deploymentBucket` to `provider.deploymentBucketObject` it creates the bucket, but also the normal serverless one and doesn't use the one I specified

I'm sure it's me, but this was working a week ago!

**Comment by Enase** [comment]
+1

**Comment by MikeSouza** [comment]
It appears that in `v2.10.0` changes were made (https://github.com/serverless/serverless/pull/8460).

@Enase It may fix it for `>= v2.10.0`, but it is not backwards compatible.

A version check will need to be made to support `<= v2.9.0`.

**Comment by Enase** [comment]
@MikeSouza Could we add a quick fix [here](https://github.com/MikeSouza/serverless-deployment-bucket/blob/master/lib/index.js#L14), like:

```
const semver = require('semver');

...

const configPath = semver.gt(serverless.version, '2.9.0')
    ? 'provider.deploymentBucket'
    : 'provider.deploymentBucketObject';
this.deploymentBucket = get(this.serverless.service, configPath, {})
```

and yes, you will need for semver dependency in `package.json`

**Comment by MikeSouza** [comment]
I have a fix pending, but it won't be released until tomorrow.  Quite busy today.

**Comment by Enase** [comment]
@MikeSouza Thanks a lot! One day is not a big dial.

**Comment by MikeSouza** [comment]
The fix is not difficult, but as with all best practices, I have to spend the time to update the failing tests and maintain 100% code coverage.

**Comment by jameswoodley** [comment]
Thanks @MikeSouza for jumping on this. Let me know if any help or testing is needed!

**Comment by MikeSouza** [comment]
Should be fixed now.
