### ISSUE TITLE
Failure for tag deployment when first creating the bucket

### ISSUE THREAD

**Issue by twosdai** [MikeSouza/serverless-deployment-bucket#39]
**Background**
Hey this issue is in relation to https://github.com/MikeSouza/serverless-deployment-bucket/pull/36

**Details**
Specifically there is a bug in processing tags for a new bucket
The following function which is used to make a `boolean` check to either add or skip tagging
```js 
async hasChangedBucketTags(name, tags) {
    try {
      const response = await this.provider.request('S3', 'getBucketTagging', { Bucket: name })
      return response && JSON.stringify(response.TagSet) !== JSON.stringify(tags)
    } catch (e) {
      return false
    }
  }
  ```
  
The above function will throw an error and return false everytime for a new bucket, and there is no process for adding tags separately. Outside of manually adding a dummy tag to the S3 bucket after creation and then rerunning the `serverless deploy` step. 

**Expected Outcome**

* when the S3 bucket is created for the first time we should add tags to the creation if any exist

* Bonus Points: error processing for `hasChangedBucketTags`  could also be updated to check to see if the error is specific for no-tags, and then attempt to add tags if any existed in the serverless.yml file.

**Comment by MikeSouza** [comment]
Fixed in PR #42.  Released in v1.4.3.
