### ISSUE TITLE
Update to support custom KMS Keys

### ISSUE THREAD

**Issue by jeremy-london** [MikeSouza/serverless-deployment-bucket#46]
Currently there is no way to pass config to the KMS key configuration block

```js
ApplyServerSideEncryptionByDefault: {
    SSEAlgorithm: sseAlgorithm,
    KMSMasterKeyID: kmsMasterKeyId
}
```

The current call only passes 2 of 3 params with no way of getting that 3rd param sent through:
Caller:
https://github.com/MikeSouza/serverless-deployment-bucket/blob/0c9c632170aeb2284b2e5c3f4669f5e81442353a/lib/index.js#L239

Function:
https://github.com/MikeSouza/serverless-deployment-bucket/blob/0c9c632170aeb2284b2e5c3f4669f5e81442353a/lib/index.js#L96

**Comment by MikeSouza** [comment]
Released in v1.5.0
