### ISSUE TITLE
bucket is created when using sls package

### ISSUE THREAD

**Issue by fracmak** [MikeSouza/serverless-deployment-bucket#6]
When running `sls package`, it triggers `Creating deployment bucket` which actually creates AWS resources. The creation of the bucket should only happen on deploy

**Comment by MikeSouza** [comment]
I agree that it is not ideal to that the deployment bucket gets created on an `sls package`. 
 Unfortunately, looking into this further, given the lifecycle hooks available to plugins, there is not an ideal hook to use that will result in your desired behavior (as far as I have explored). There is also no way for the hooked event handler to know which command (`deploy` or `package`) triggered it.

You're more than welcome to find an alternative solution and submit a PR if I'm missing something.
