### ISSUE TITLE
policy needs a better example

### ISSUE THREAD

**Issue by jjmartin** [MikeSouza/serverless-deployment-bucket#7]
Could you provide a better example of applying a policy to the deployment bucket?

is it possible to refer to the deployment bucket name in the policy? 

can i do a policy on the bucket without renaming the bucket? (if i add this to an existing stack/serverless deployment, what happens? )

**Comment by MikeSouza** [comment]
Sorry, this feature was not well thought out. It was added, but I never ended up using/ needing it. It's the raw JSON policy. So if you're trying to do anything complex where the policy must reference dynamic values or anything, then it's going to be rather cumbersome to use.
